build:
  maxIssues: 0

naming:
  FunctionNaming:
    active: false
  TopLevelPropertyNaming:
    active: true
    constantPattern: '[A-Z][_A-Z0-9]*'

style:
  MagicNumber:
    active: false

  WildcardImport:
    active: false

  MaxLineLength:
    active: true
    maxLineLength: 120

complexity:
  LongMethod:
    active: true
    threshold: 60

  LongParameterList:
    active: true
    threshold: 10

  TooManyFunctions:
    active: true
    thresholdInClasses: 15

comments:
  UndocumentedPublicFunction:
    active: false

formatting:
  NoConsecutiveBlankLines:
    active: true

